/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schooldiary;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class AddEditForm extends javax.swing.JFrame {

    /**
     * Creates new form AddEditForm
     */
    int rowIndex = -1;
    int id ;
    DefaultTableModel model;
    public AddEditForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }
    public AddEditForm(int rowIndex) {
        initComponents();
        setLocationRelativeTo(null);
        this.rowIndex = rowIndex;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jTextField_EmriMbiemri = new javax.swing.JTextField();
        jTextField_DetyratEShtepise = new javax.swing.JTextField();
        jTextField_AngazhimiIndividual = new javax.swing.JTextField();
        jTextField_Prezentimet = new javax.swing.JTextField();
        jButton_Clear = new javax.swing.JButton();
        jTextField_Seminar = new javax.swing.JTextField();
        jTextField_Kriteri = new javax.swing.JTextField();
        jTextField_VP1 = new javax.swing.JTextField();
        jTextField_DetyraKontrolluese = new javax.swing.JTextField();
        jTextField_TestPermbledhes = new javax.swing.JTextField();
        jTextField_VP2 = new javax.swing.JTextField();
        jTextField_NotaPerfundimtare = new javax.swing.JTextField();
        jTextField_Nr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Nr.");

        jLabel2.setText("Emri dhe Mbiemri:");

        jLabel3.setText("Detyrat e shtepise:");

        jLabel4.setText("Angazhimi individual:");

        jLabel5.setText("Prezentimet:");

        jLabel6.setText("Seminar:");

        jLabel7.setText("Kriteri:");

        jLabel8.setText("VP 1:");

        jLabel9.setText("Detyra kontrolluese:");

        jLabel10.setText("Test permbledhes:");

        jLabel11.setText("VP 2:");

        jLabel12.setText("Nota perfundimtare:");

        jButton_Cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-close.png"))); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-save.png"))); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-clear.png"))); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jTextField_Seminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SeminarActionPerformed(evt);
            }
        });

        jTextField_VP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField_VP2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField_NotaPerfundimtare.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_EmriMbiemri, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jTextField_DetyratEShtepise)
                        .addComponent(jTextField_AngazhimiIndividual)
                        .addComponent(jTextField_Prezentimet)
                        .addComponent(jTextField_Seminar)
                        .addComponent(jTextField_Kriteri)
                        .addComponent(jTextField_VP1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_DetyraKontrolluese)
                        .addComponent(jTextField_TestPermbledhes)
                        .addComponent(jTextField_VP2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_NotaPerfundimtare, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_Nr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel1)
                                                                    .addComponent(jTextField_Nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel2)
                                                                    .addComponent(jTextField_EmriMbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(24, 24, 24)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel3)
                                                                    .addComponent(jTextField_DetyratEShtepise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel4))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField_AngazhimiIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(24, 24, 24)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jTextField_Prezentimet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(23, 23, 23)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jTextField_Seminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(27, 27, 27)
                                                        .addComponent(jLabel7))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jTextField_Kriteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jTextField_VP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField_DetyraKontrolluese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField_TestPermbledhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_VP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_NotaPerfundimtare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_SeminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SeminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SeminarActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        
        int nr = Integer.valueOf(jTextField_Nr.getText());
        String emriMbiemri = jTextField_EmriMbiemri.getText();
        String detyratEShtepise = jTextField_DetyratEShtepise.getText();
        String angazhimiIndividual = jTextField_AngazhimiIndividual.getText();
        String prezentimet = jTextField_Prezentimet.getText();
        String seminar = jTextField_Seminar.getText();
        String kriteri = jTextField_Kriteri.getText();
        String vp1 = jTextField_VP1.getText();
        String detyraKontrolluese = jTextField_DetyraKontrolluese.getText();
        String testPermbledhes = jTextField_TestPermbledhes.getText();
        String vp2 = jTextField_VP2.getText();
        String notaPerfundimtare = jTextField_NotaPerfundimtare.getText();        
        
         Manage mng = new Manage();
         
        if (rowIndex == -1 ) { 
         
          if(!mng.isNrStudentExist(ClassFrame.table,nr)) {  
            
        mng.addStudent(ClassFrame.table,nr, emriMbiemri, detyratEShtepise, angazhimiIndividual, prezentimet, seminar, kriteri, vp1, detyraKontrolluese, testPermbledhes, vp2, notaPerfundimtare);
      
        jTextField_Nr.setText(null);
        jTextField_EmriMbiemri.setText(null);
        jTextField_DetyratEShtepise.setText(null);
        jTextField_AngazhimiIndividual.setText(null);
        jTextField_Prezentimet.setText(null);
        jTextField_Seminar.setText(null);
        jTextField_Kriteri.setText(null);
        jTextField_VP1.setText(null);
        jTextField_DetyraKontrolluese.setText(null);
        jTextField_TestPermbledhes.setText(null);
        jTextField_VP2.setText(null);
        jTextField_NotaPerfundimtare.setText(null);
          }else {
              JOptionPane.showMessageDialog(null, "Ky Nr i nxenesit ekziston..");
          }
        }
        else {
            
        mng.editStudent(ClassFrame.table,nr, emriMbiemri, detyratEShtepise, angazhimiIndividual, prezentimet, seminar, kriteri, vp1, detyraKontrolluese, testPermbledhes, vp2, notaPerfundimtare);
             
        }
       
        try {
            
            ClassFrame.jTableManageStudents.setModel(new DefaultTableModel(null, new Object[]{"Nr", "Emri dhe Mbiemri","Detyrat e Shtepise 30%",                                                                                        "Angazhimi Individual 30%",
                                                                                    "Prezantimet 30%", "Seminar 10%", "Kriteri (Rezultati)", "VP 1", "Detyrat Kontrolluese", "Test Permbledhes",
                                                                                         "VP 2", "Nota Perfundimtare"}));
            mng.fillStudentJtable(ClassFrame.table,ClassFrame.jTableManageStudents);
            if (ClassFrame.jTableManageStudents.getColumnModel().getColumnCount() > 0) {
    ClassFrame.jTableManageStudents.getColumnModel().getColumn(0).setPreferredWidth(6);
    ClassFrame.jTableManageStudents.getColumnModel().getColumn(1).setPreferredWidth(120);
    ClassFrame.jTableManageStudents.getColumnModel().getColumn(7).setPreferredWidth(6);
    ClassFrame.jTableManageStudents.getColumnModel().getColumn(10).setPreferredWidth(6);
    ClassFrame.jTableManageStudents.getColumnModel().getColumn(11).setPreferredWidth(30);
}
            ClassFrame.jTableManageStudents.setAutoCreateRowSorter(true);
        
        }catch(Exception ex ){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_SaveActionPerformed

    public JTextField getjTextField_AngazhimiIndividual() {
        return jTextField_AngazhimiIndividual;
    }

    public void setjTextField_AngazhimiIndividual(JTextField jTextField_AngazhimiIndividual) {
        this.jTextField_AngazhimiIndividual = jTextField_AngazhimiIndividual;
    }

    public JTextField getjTextField_DetyraKontrolluese() {
        return jTextField_DetyraKontrolluese;
    }

    public void setjTextField_DetyraKontrolluese(JTextField jTextField_DetyraKontrolluese) {
        this.jTextField_DetyraKontrolluese = jTextField_DetyraKontrolluese;
    }

    public JTextField getjTextField_DetyratEShtepise() {
        return jTextField_DetyratEShtepise;
    }

    public void setjTextField_DetyratEShtepise(JTextField jTextField_DetyratEShtepise) {
        this.jTextField_DetyratEShtepise = jTextField_DetyratEShtepise;
    }

    public JTextField getjTextField_EmriMbiemri() {
        return jTextField_EmriMbiemri;
    }

    public void setjTextField_EmriMbiemri(JTextField jTextField_EmriMbiemri) {
        this.jTextField_EmriMbiemri = jTextField_EmriMbiemri;
    }

    public JTextField getjTextField_Kriteri() {
        return jTextField_Kriteri;
    }

    public void setjTextField_Kriteri(JTextField jTextField_Kriteri) {
        this.jTextField_Kriteri = jTextField_Kriteri;
    }

    public JTextField getjTextField_NotaPerfundimtare() {
        return jTextField_NotaPerfundimtare;
    }

    public void setjTextField_NotaPerfundimtare(JTextField jTextField_NotaPerfundimtare) {
        this.jTextField_NotaPerfundimtare = jTextField_NotaPerfundimtare;
    }

    public JTextField getjTextField_Nr() {
        return jTextField_Nr;
    }

    public void setjTextField_Nr(JTextField jTextField_Nr) {
        this.jTextField_Nr = jTextField_Nr;
    }

    public JTextField getjTextField_Prezentimet() {
        return jTextField_Prezentimet;
    }

    public void setjTextField_Prezentimet(JTextField jTextField_Prezentimet) {
        this.jTextField_Prezentimet = jTextField_Prezentimet;
    }

    public JTextField getjTextField_Seminar() {
        return jTextField_Seminar;
    }

    public void setjTextField_Seminar(JTextField jTextField_Seminar) {
        this.jTextField_Seminar = jTextField_Seminar;
    }

    public JTextField getjTextField_TestPermbledhes() {
        return jTextField_TestPermbledhes;
    }

    public void setjTextField_TestPermbledhes(JTextField jTextField_TestPermbledhes) {
        this.jTextField_TestPermbledhes = jTextField_TestPermbledhes;
    }

    public JTextField getjTextField_VP1() {
        return jTextField_VP1;
    }

    public void setjTextField_VP1(JTextField jTextField_VP1) {
        this.jTextField_VP1 = jTextField_VP1;
    }

    public JTextField getjTextField_VP2() {
        return jTextField_VP2;
    }

    public void setjTextField_VP2(JTextField jTextField_VP2) {
        this.jTextField_VP2 = jTextField_VP2;
    }

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        
        jTextField_Nr.setText(null);
        jTextField_EmriMbiemri.setText(null);
        jTextField_DetyratEShtepise.setText(null);
        jTextField_AngazhimiIndividual.setText(null);
        jTextField_Prezentimet.setText(null);
        jTextField_Seminar.setText(null);
        jTextField_Kriteri.setText(null);
        jTextField_VP1.setText(null);
        jTextField_DetyraKontrolluese.setText(null);
        jTextField_TestPermbledhes.setText(null);
        jTextField_VP2.setText(null);
        jTextField_NotaPerfundimtare.setText(null);
        
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_AngazhimiIndividual;
    private javax.swing.JTextField jTextField_DetyraKontrolluese;
    private javax.swing.JTextField jTextField_DetyratEShtepise;
    private javax.swing.JTextField jTextField_EmriMbiemri;
    private javax.swing.JTextField jTextField_Kriteri;
    private javax.swing.JTextField jTextField_NotaPerfundimtare;
    private javax.swing.JTextField jTextField_Nr;
    private javax.swing.JTextField jTextField_Prezentimet;
    private javax.swing.JTextField jTextField_Seminar;
    private javax.swing.JTextField jTextField_TestPermbledhes;
    private javax.swing.JTextField jTextField_VP1;
    private javax.swing.JTextField jTextField_VP2;
    // End of variables declaration//GEN-END:variables
}
