/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schooldiary;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class ClassFrame extends javax.swing.JFrame {

   Manage mng = new Manage();
    DefaultTableModel model;
    static String table;
    static String text;
    
    public ClassFrame() {
        initComponents();
        mng.fillStudentJtable(table,jTableManageStudents);
        model  = (DefaultTableModel)jTableManageStudents.getModel();
        jTableManageStudents.setAutoCreateRowSorter(true);
        jTableManageStudents.setRowHeight(30);
        jTableManageStudents.setShowGrid(true);
        jTableManageStudents.setGridColor(Color.lightGray);
        jTableManageStudents.setSelectionBackground(Color.BLACK);
        
    }
    public ClassFrame(String table,String text) {
        this.table = table;
        this.text = text;
        initComponents();
        mng.fillStudentJtable(table,jTableManageStudents);
        mng.fillTextJtable(text, jTableText);
        model  = (DefaultTableModel)jTableManageStudents.getModel();
        model  = (DefaultTableModel)jTableText.getModel();
        jTableManageStudents.setAutoCreateRowSorter(true);
        jTableManageStudents.setRowHeight(30);
        jTableManageStudents.setShowGrid(true);
        jTableManageStudents.setGridColor(Color.BLACK);
        jTableManageStudents.setSelectionBackground(Color.BLACK);
        
        jTableText.setShowGrid(true);
        jTableText.setRowHeight(30);
        jTableText.setGridColor(Color.yellow);
        jTableText.setSelectionBackground(Color.DARK_GRAY);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageStudents = new javax.swing.JTable();
        jButton_Delete = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_New = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_IdText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableText = new javax.swing.JTable();
        jButton_AddText = new javax.swing.JButton();
        jButton_EditText = new javax.swing.JButton();
        jButton_DeleteText = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 230, 220));

        jTableManageStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr.", "Emri dhe Mbiemri", "Detyrat e shtepise 30%", "Angazhimi Individual 30%", "Prezantimet 30%", "Seminar 10%", "Kriteri (Rezultati)l", "VP1", "Detyra Kontrolluese", "Test Permbledhes", "VP 2", "Nota Perfundimtare"
            }
        ));
        jScrollPane1.setViewportView(jTableManageStudents);
        if (jTableManageStudents.getColumnModel().getColumnCount() > 0) {
            jTableManageStudents.getColumnModel().getColumn(0).setPreferredWidth(6);
            jTableManageStudents.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableManageStudents.getColumnModel().getColumn(7).setPreferredWidth(6);
            jTableManageStudents.getColumnModel().getColumn(10).setPreferredWidth(6);
            jTableManageStudents.getColumnModel().getColumn(11).setPreferredWidth(30);
        }

        jButton_Delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-close.png"))); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-edit.png"))); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_New.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-new.png"))); // NOI18N
        jButton_New.setText("New");
        jButton_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Text:");

        jTextField_IdText.setEditable(false);
        jTextField_IdText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTableText.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Text", "Id"
            }
        ));
        jTableText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTextMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableText);
        if (jTableText.getColumnModel().getColumnCount() > 0) {
            jTableText.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableText.getColumnModel().getColumn(1).setPreferredWidth(650);
            jTableText.getColumnModel().getColumn(2).setPreferredWidth(1);
        }

        jButton_AddText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AddText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-new.png"))); // NOI18N
        jButton_AddText.setText("Add");
        jButton_AddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddTextActionPerformed(evt);
            }
        });

        jButton_EditText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EditText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-edit.png"))); // NOI18N
        jButton_EditText.setText("Change");
        jButton_EditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditTextActionPerformed(evt);
            }
        });

        jButton_DeleteText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_DeleteText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-close.png"))); // NOI18N
        jButton_DeleteText.setText("Delete");
        jButton_DeleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteTextActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(150, 150, 150));
        jLabel4.setText("=======================================");

        jLabel5.setForeground(new java.awt.Color(150, 150, 150));
        jLabel5.setText("=====================================");

        jLabel6.setForeground(new java.awt.Color(150, 150, 150));
        jLabel6.setText("=====================================");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_New, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_DeleteText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_EditText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AddText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 152, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jTextField_IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jButton_AddText)
                            .addGap(40, 40, 40)
                            .addComponent(jButton_EditText)
                            .addGap(40, 40, 40)
                            .addComponent(jButton_DeleteText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_New))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NewActionPerformed

        AddEditForm aef = new AddEditForm();
        aef.setVisible(true);
        aef.setLocationRelativeTo(null);
        aef.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton_NewActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        model = (DefaultTableModel)jTableManageStudents.getModel();
        int rowIndex = jTableManageStudents.getSelectedRow();
        if (rowIndex>=0) {
            //System.out.println("Vlera rowIndex = "+rowIndex);
            AddEditForm aef = new AddEditForm(rowIndex);
            aef.setVisible(true);
            aef.setLocationRelativeTo(null);
            aef.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            aef.getjTextField_Nr().setText(model.getValueAt(rowIndex, 0).toString());
            aef.getjTextField_EmriMbiemri().setText(model.getValueAt(rowIndex, 1).toString());
            aef.getjTextField_DetyratEShtepise().setText(model.getValueAt(rowIndex, 2).toString());
            aef.getjTextField_AngazhimiIndividual().setText(model.getValueAt(rowIndex, 3).toString());
            aef.getjTextField_Prezentimet().setText(model.getValueAt(rowIndex, 4).toString());
            aef.getjTextField_Seminar().setText(model.getValueAt(rowIndex, 5).toString());
            aef.getjTextField_Kriteri().setText(model.getValueAt(rowIndex, 6).toString());
            aef.getjTextField_VP1().setText(model.getValueAt(rowIndex, 7).toString());
            aef.getjTextField_DetyraKontrolluese().setText(model.getValueAt(rowIndex, 8).toString());
            aef.getjTextField_TestPermbledhes().setText(model.getValueAt(rowIndex, 9).toString());
            aef.getjTextField_VP2().setText(model.getValueAt(rowIndex, 10).toString());
            aef.getjTextField_NotaPerfundimtare().setText(model.getValueAt(rowIndex, 11).toString());

        }
        else {

            JOptionPane.showMessageDialog(null, "Asnje nxenes i selektuar..");

        }

    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        model = (DefaultTableModel)jTableManageStudents.getModel();
        int rowIndex = jTableManageStudents.getSelectedRow();
        
        if (rowIndex>=0) {

            int nr = Integer.valueOf(model.getValueAt(rowIndex, 0).toString());
            mng.deleteStudent(table,nr);

            jTableManageStudents.setModel(new DefaultTableModel(null, new Object[]{"Nr", "Emri dhe Mbiemri","Detyrat e Shtepise 30%",                                                                                        "Angazhimi Individual 30%",
                "Prezantimet 30%", "Seminar 10%", "Kriteri (Rezultati)", "VP 1", "Detyrat Kontrolluese", "Test Permbledhes",
                "VP 2", "Nota Perfundimtare"}));
    if (jTableManageStudents.getColumnModel().getColumnCount() > 0) {
    jTableManageStudents.getColumnModel().getColumn(0).setPreferredWidth(6);
    jTableManageStudents.getColumnModel().getColumn(1).setPreferredWidth(120);
    jTableManageStudents.getColumnModel().getColumn(7).setPreferredWidth(6);
    jTableManageStudents.getColumnModel().getColumn(10).setPreferredWidth(6);
    jTableManageStudents.getColumnModel().getColumn(11).setPreferredWidth(30);
}
    mng.fillStudentJtable(table,jTableManageStudents);
    jTableManageStudents.setAutoCreateRowSorter(true);

    }
    else {

        JOptionPane.showMessageDialog(null, "Asnje nxenes i selektuar..");

        }

    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_AddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddTextActionPerformed
      SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
      String date = dateFormat.format(jDateChooser1.getDate());
      String msgText = jTextArea1.getText();
      
     mng.addText(text, null, date, msgText);
    
     jTableText.setModel(new DefaultTableModel(null, new Object[]{"Date","Text","Id"}));
     if (jTableText.getColumnModel().getColumnCount() > 0) {
    jTableText.getColumnModel().getColumn(0).setPreferredWidth(150);
    jTableText.getColumnModel().getColumn(1).setPreferredWidth(650);
    jTableText.getColumnModel().getColumn(2).setPreferredWidth(1);
}
     mng.fillTextJtable(text, jTableText);
     jDateChooser1.setDate(null);
     jTextArea1.setText(null);
    }//GEN-LAST:event_jButton_AddTextActionPerformed

    private void jButton_DeleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteTextActionPerformed
        
         model = (DefaultTableModel)jTableText.getModel();
        int rowIndex = jTableText.getSelectedRow();
        
        if (rowIndex>=0) {

            int id = Integer.valueOf(model.getValueAt(rowIndex, 2).toString());
            mng.deleteText(text, id);

            jTableText.setModel(new DefaultTableModel(null, new Object[]{"Date","Text","Id"}));
            if (jTableText.getColumnModel().getColumnCount() > 0) {
    jTableText.getColumnModel().getColumn(0).setPreferredWidth(150);
    jTableText.getColumnModel().getColumn(1).setPreferredWidth(650);
    jTableText.getColumnModel().getColumn(2).setPreferredWidth(1);
}
    mng.fillTextJtable(text,jTableText);
    
    }
    else {

        JOptionPane.showMessageDialog(null, "Asnje nxenes i selektuar..");

        }
        jTextField_IdText.setText(null);
        jDateChooser1.setDate(null);
        jTextArea1.setText(null);
        
    }//GEN-LAST:event_jButton_DeleteTextActionPerformed

    private void jTableTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTextMouseClicked
        
        model = (DefaultTableModel)jTableText.getModel();
       int rowIndex = jTableText.getSelectedRow();
        jTextField_IdText.setText(model.getValueAt(rowIndex, 2).toString());
        
      Date bDate = null ;
        try {
            bDate = new SimpleDateFormat("dd-MM-yyyy").parse(model.getValueAt(rowIndex, 0).toString());
            jDateChooser1.setDate(bDate);
        } catch (ParseException ex) {
            Logger.getLogger(ClassFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextArea1.setText(model.getValueAt(rowIndex, 1).toString());
        
        
    }//GEN-LAST:event_jTableTextMouseClicked

    private void jButton_EditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditTextActionPerformed
        
        model = (DefaultTableModel)jTableText.getModel();
        int rowIndex = jTableText.getSelectedRow();
        
        SimpleDateFormat bdate = new SimpleDateFormat("dd-MM-yyyy");
        String date = bdate.format(jDateChooser1.getDate());
        
        String msgText = jTextArea1.getText();
        int id = Integer.valueOf(jTextField_IdText.getText());
        
        if (rowIndex>=0) {
            
            mng.editText(text, id, date, msgText);
            jTableText.setModel(new DefaultTableModel(null, new Object[]{"Date","Text","Id"}));
            if (jTableText.getColumnModel().getColumnCount() > 0) {
    jTableText.getColumnModel().getColumn(0).setPreferredWidth(150);
    jTableText.getColumnModel().getColumn(1).setPreferredWidth(650);
    jTableText.getColumnModel().getColumn(2).setPreferredWidth(1);
}
            mng.fillTextJtable(text,jTableText);
        }
        else {

            JOptionPane.showMessageDialog(null, "Asnje nxenes i selektuar..");

        }        
        
    }//GEN-LAST:event_jButton_EditTextActionPerformed

    public JTable getjTableManageStudents() {
        return jTableManageStudents;
    }

    public void setjTableManageStudents(JTable jTableManageStudents) {
        this.jTableManageStudents = jTableManageStudents;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddText;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_DeleteText;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_EditText;
    private javax.swing.JButton jButton_New;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableManageStudents;
    public static javax.swing.JTable jTableText;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_IdText;
    // End of variables declaration//GEN-END:variables
}
