/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schooldiary;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class EnterFrame extends javax.swing.JFrame {

    /**
     * Creates new form EnterFrame
     */
    public EnterFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Class_6_5 = new javax.swing.JButton();
        jButton_Class_6_4 = new javax.swing.JButton();
        jButton_Class_9_5 = new javax.swing.JButton();
        jButton_Class_7_5 = new javax.swing.JButton();
        jButton_Class_8_5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ravie", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("School Diary");

        jButton_Class_6_5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_Class_6_5.setForeground(new java.awt.Color(255, 102, 102));
        jButton_Class_6_5.setText("Class 6_5");
        jButton_Class_6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Class_6_5ActionPerformed(evt);
            }
        });

        jButton_Class_6_4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_Class_6_4.setForeground(new java.awt.Color(255, 102, 102));
        jButton_Class_6_4.setText("Class 6_4");
        jButton_Class_6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Class_6_4ActionPerformed(evt);
            }
        });

        jButton_Class_9_5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_Class_9_5.setForeground(new java.awt.Color(255, 102, 102));
        jButton_Class_9_5.setText("Class 9_5");
        jButton_Class_9_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Class_9_5ActionPerformed(evt);
            }
        });

        jButton_Class_7_5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_Class_7_5.setForeground(new java.awt.Color(255, 102, 102));
        jButton_Class_7_5.setText("Class 7_5");
        jButton_Class_7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Class_7_5ActionPerformed(evt);
            }
        });

        jButton_Class_8_5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_Class_8_5.setForeground(new java.awt.Color(255, 102, 102));
        jButton_Class_8_5.setText("Class 8_5");
        jButton_Class_8_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Class_8_5ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-book.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Class_7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Class_8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton_Class_6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton_Class_6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton_Class_9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jButton_Class_6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Class_7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton_Class_6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addGap(17, 17, 17)
                .addComponent(jButton_Class_8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_Class_9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Class_6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Class_6_5ActionPerformed
       //name of database table is class6_5
        String table = jButton_Class_6_5.getText().toLowerCase().replaceAll("\\s", "");
        //name of database table is c6_5
        String text1 = jButton_Class_6_5.getText().toLowerCase().replaceAll("\\s", "");
        String text = "c"+text1.substring(text1.length()-3, text1.length());
        ClassFrame cf = new ClassFrame(table,text);
        cf.setVisible(true);
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
        cf.pack();
    
    }//GEN-LAST:event_jButton_Class_6_5ActionPerformed

    private void jButton_Class_6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Class_6_4ActionPerformed
        //name of database table is class6_4
        String table = jButton_Class_6_4.getText().toLowerCase().replaceAll("\\s", "");
        //name of database table is c6_4
        String text1 = jButton_Class_6_4.getText().toLowerCase().replaceAll("\\s", "");
        String text = "c"+text1.substring(text1.length()-3, text1.length());
        ClassFrame cf = new ClassFrame(table,text);
        cf.setVisible(true);
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        cf.setLocationRelativeTo(null);
        cf.pack();
        
        
    }//GEN-LAST:event_jButton_Class_6_4ActionPerformed

    private void jButton_Class_9_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Class_9_5ActionPerformed
       
        //name of database table is class9_5
        String table = jButton_Class_9_5.getText().toLowerCase().replaceAll("\\s", "");
        //name of database table is c9_5
        String text1 = jButton_Class_9_5.getText().toLowerCase().replaceAll("\\s", "");
        String text = "c"+text1.substring(text1.length()-3, text1.length());
        ClassFrame cf = new ClassFrame(table,text);
        cf.setVisible(true);
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        cf.setLocationRelativeTo(null);
        cf.pack();
        
    }//GEN-LAST:event_jButton_Class_9_5ActionPerformed

    private void jButton_Class_7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Class_7_5ActionPerformed
       
        //name of database table is class7_5
        String table = jButton_Class_7_5.getText().toLowerCase().replaceAll("\\s", "");
        //name of database table is c7_5
        String text1 = jButton_Class_7_5.getText().toLowerCase().replaceAll("\\s", "");
        String text = "c"+text1.substring(text1.length()-3, text1.length());
        ClassFrame cf = new ClassFrame(table,text);
        cf.setVisible(true);
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        cf.setLocationRelativeTo(null);
        cf.pack();
        
    }//GEN-LAST:event_jButton_Class_7_5ActionPerformed

    private void jButton_Class_8_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Class_8_5ActionPerformed
        
        //name of database table is class8_5
        String table = jButton_Class_8_5.getText().toLowerCase().replaceAll("\\s", "");
        //name of database table is c8_5
        String text1 = jButton_Class_8_5.getText().toLowerCase().replaceAll("\\s", "");
        String text = "c"+text1.substring(text1.length()-3, text1.length());
        ClassFrame cf = new ClassFrame(table,text);
        cf.setVisible(true);
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        cf.setLocationRelativeTo(null);
        cf.pack();
        
    }//GEN-LAST:event_jButton_Class_8_5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Class_6_4;
    private javax.swing.JButton jButton_Class_6_5;
    private javax.swing.JButton jButton_Class_7_5;
    private javax.swing.JButton jButton_Class_8_5;
    private javax.swing.JButton jButton_Class_9_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
